### ISSUE TITLE
submission web form

### ISSUE THREAD

**Issue by aburrell** [EquitableLettersSP/ELSP#15]
Create a web form for submitting letters.

**Comment by johncoxon** [comment]
I'm not sure how useful it is to be able to do this – ultimately all a web form will do is send us an email, and we then run into potential data privacy issues with having user information cached on a web server, so I'm not sure I support this idea. What do other people think? (Same question for #16.)

**Comment by aburrell** [comment]
Talked about this and #16 with @katieefrey.  She made the point that web forms can introduce problems with submitting files of different formats.  So if we aren't getting bombarded with spam, we might as well close these.  If things change, we can open them again.
