### ISSUE TITLE
FERPA Link

### ISSUE THREAD

**Issue by aburrell** [EquitableLettersSP/ELSP#17]
After our discussion of student privacy issues, I thought this link may be useful to include in our letter writing resources:  https://www.cnm.edu/depts/dean-of-students/faculty-resources/ferpa-and-student-recommendations-references

**Comment by aburrell** [comment]
And another link with good examples and a breakdown of why they're good: https://blog.prepscholar.com/4-amazing-recommendation-letter-samples

**Comment by mjonesjr** [comment]
# Words for Website and links about FERPA
We ask that all submitters to ELSP stay in accordance with FERPA laws and blackout/remove any non-directory personally identifiable information (PII) or non-directory education records that fall under FERPA Protections prior to submitting letters to ELSP. If ELSP is in receipt of a letter potentially containing PII and or non-directory education records that may fall under FERPA Protections, the letter will be returned to the submitter to remove the information in question.

Links to point submitters to:
U.S. Department of Education: https://www2.ed.gov/policy/gen/guid/fpco/ferpa/index.html
University of Wyoming: https://www.uwyo.edu/registrar/ferpa/ferpa_parents.html
Fordham University: https://www.fordham.edu/download/downloads/id/1850/09_-_dos_and_donts_for_teachers.pdf
Forbes:  https://www.forbes.com/sites/willarddix/2018/05/16/you-need-to-understand-your-educational-privacy-rights/?sh=5891e7e46b93
Penn State University Registrar: https://www.registrar.psu.edu/confidentiality/ferpa-frequently-asked-questions.cfm#2
NACE: https://www.naceweb.org/public-policy-and-legal/legal-issues/ferpa-primer-the-basics-and-beyond/

**Comment by melissaroses** [comment]
added provided links to resources page
