### ISSUE TITLE
ENH: Needs to be clearer how to interact with us on our front page?

### ISSUE THREAD

**Issue by johncoxon** [EquitableLettersSP/ELSP#35]
For context, I'm writing an abstract to introduce us to the NAM audience. I started by taking the mission from our front page, "Encouraging merit-based recommendations and nominations in the space physics community by providing resources and reviews", which is what we do, but it doesn't say how we do it – it doesn't ask for volunteers, or explain the intended workflow, or similar.

I'd like to suggest we add something to the front page which says something like the following:

**Our Method**
If you are writing a recommendation letter for someone you know professionally, you can send it to us ([insert how to do this here]) and we will send it out to our reviewers. They will provide recommendations on how you can make your letter more equitable and less biased, using a combination of the techniques and resources described elsewhere on our site, with the aim to make unbiased recommendation letters more accessible to all. If you are interested in being a reviewer, please let us know by [insert how to do this here].

What do people think?

**Comment by aburrell** [comment]
I like this!  Definitely belongs on the homepage.
