### ISSUE TITLE
ENH: style guide for letter writing

### ISSUE THREAD

**Issue by aburrell** [EquitableLettersSP/ELSP#37]
In Meeting 14, @johncoxon brought up that it would be useful to have a style guide to point people to.  This came up because we were doing a group review of a sample letter and found that we expected a certain style of formatting and didn't have a general grammer reason for some of the choices.  John suggested using JGR, since it's one of the most prolific journals in our field: https://www.agu.org/Publish-with-AGU/Publish/Author-Resources/Grammar-Style-Guide

This link could be included under letter-writing resources.

**Comment by AJHalford** [comment]
I think in the style guide we might also want to mention how it's good to use the same style/word choices as the group you are nominating/recommending to.
